### ISSUE TITLE
三级菜单显示有文档，会出现左边的菜单

### ISSUE THREAD

**Issue by 1181888200** [febsteam/FEBS-Cloud-Web#5]
![image](https://user-images.githubusercontent.com/12285178/103337885-95586180-4ab7-11eb-951c-c5786f670984.png)
不知道是我配置问题还是什么原因造成的，一级和二级的组件都配置了Layout

**Comment by wuyouzhuguli** [comment]
演示环境不是有三级菜单demo吗

**Comment by wuyouzhuguli** [comment]
![Uploading QQ20201230-160026@2x.png…]()

**Comment by 1181888200** [comment]
因为我看到演示环境的三级菜单上面的那个 配置了一个二级菜单页面【demos/two/Index】，但是那个这个页面又不会打开，那么就会一直在项目里

**Comment by 1181888200** [comment]
已经解决了，由于二级菜单里面有一个Index.vue 是用于Layout以外的栏目菜单配置，建议独立出去作为组件，不然配置的时候很容易和其他文件的Index.vue混淆
